---
# tasks file for appserver
- name: create nodeapp directory
  file:
    path: "{{ folderpath }}" 
    state: directory
    mode: 0755
- name: Download node js package setup
  command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{folderpath}}/nodesource_setup.sh"
- name: Execute downloaded shell script
  command: "sudo bash {{folderpath}}/nodesource_setup.sh"
- name: Installing node js
  apt:
    name: nodejs
    state: present
- name: Copy the code
  template:
    src: templates/hello.js.j2
    dest: "{{ folderpath }}/hello.js"
- name: Install pm2
  npm:
    name: pm2
    global: yes
- name: start node js app
  command: "pm2 start -f {{ folderpath }}/hello.js"